# notification-service - local profile
spring:
  cloud:
    config:
      enabled: false
  jpa:
    show-sql: true
  flyway:
    clean-disabled: false
    repair-on-migrate: true
logging:
  level:
    com.ioes: DEBUG
    org.springframework.kafka: DEBUG
